/*
- 2022년 1월 도서판매 기준
- 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가)
- 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 
- AUTHOR_ID 오름차, CATEGORY 내림차
1. BOOK AUTHOR BOOK_SALES id로 조인
2. 날짜조건 설정
2. 저자, 카테고리 그룹핑
3. 매출액 컬럼설정
4. AUTHOR_ID 오름차, CATEGORY 내림차 정렬
*/
SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE* SALES) TOTAL_SALES
FROM BOOK B
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES S ON B.BOOK_ID = s.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID, CATEGORY DESC

# SELECT A.AUTHOR_ID  ,C.AUTHOR_NAME  ,A.CATEGORY ,SUM(A.PRICE * B.SALES) AS TOTAL_SALES
# FROM BOOK A
# INNER JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID 
#                         AND B.SALES_DATE >= '20220101' AND B.SALES_DATE < '20220201'
# LEFT JOIN AUTHOR C ON A.AUTHOR_ID = C.AUTHOR_ID
# GROUP BY C.AUTHOR_ID,A.CATEGORY
# ORDER BY A.AUTHOR_ID,A.CATEGORY DESC

# SELECT *
# FROM BOOK B
#     JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
#     JOIN BOOK_SALES S ON B.BOOK_ID = s.BOOK_ID
# GROUP BY A.AUTHOR_ID, CATEGORY,