/*
1. 입양을 못간 동물 = 
2. 보호소 기간 내림차
3. 3개 제한 출력
4. 보호시작일 오름차
*/
SELECT NAME, DATETIME
FROM ANIMAL_INS 
WHERE ANIMAL_ID NOT IN(
    SELECT I.ANIMAL_ID
    FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
)
ORDER BY DATETIME
LIMIT 3