/*
- 생산일자 2022년 5월
- 식품 ID, 식품 이름, 총매출
- 총매출 desc, 식품ID asc
1. id기준 join
2. 제품명 gb
3. 가격 * 양 컬럼 설정
4. 총매출 desc, id 오름차
*/
SELECT P.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER F
ON P.PRODUCT_ID = F.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, 1