/*
12세 이하 환자 + 여자
TLNO null => 'NONE'
AGE 내림차, PT_NAME 오름차
*/
SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, 'NONE') as TLNO FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME