# Nullable 있음
# 진료과 CS or GS, 고용일자 내림차순, 이름 오름차순
# DR_NAME, DR_ID, MCDP_CD, HIRE_YMD
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, '%Y-%m-%d')
FROM doctor
WHERE MCDP_CD = 'CS' OR MCDP_CD = 'GS' 
ORDER BY HIRE_YMD DESC, DR_NAME