/*
- 완료된 중고거래 sales
- 총금액 70만 이상 그룹핑 sum
- 회원ID, 닉네임, 총거래금액 
- 총거래금액 ASC order by
*/
SELECT USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES 
FROM USED_GOODS_USER u JOIN USED_GOODS_BOARD b
ON USER_ID = WRITER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES