/*
- 리뷰 max 회원
- 회원 이름, 리뷰 텍스트, 리뷰 작성일
- 리뷰 작성일 오름차, 리뷰 텍스트 오름차
1. 가장 많은 댓글 수를 구하는 서브쿼리 작성
2. 그 댓글 수와 같은 수의 멤버 아이디 구하기
3. 해당 멤버 아이디와 같은 멤버아이디의 리뷰글을 구하기
4. REVIEW_DATE asc, MEMBER_PROFILE asc
*/
SELECT C.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE,'%Y-%m-%d')
FROM REST_REVIEW  A 
JOIN (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1)B 
ON A.MEMBER_ID = B.MEMBER_ID
LEFT JOIN MEMBER_PROFILE C ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY A.REVIEW_DATE,A.REVIEW_TEXT