/*
2022년 1월 판매도서
도서별 판매량 합산

*/
SELECT B1.CATEGORY, SUM(B2.SALES) as TOTAL_SALES
FROM BOOK B1 JOIN BOOK_SALES B2
ON B1.BOOK_ID = B2.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY B1.CATEGORY
ORDER BY B1.CATEGORY