/*
- 가격대 별
- 상품 갯수
- 가격대 오름차
*/
# SELECT ROUND(PRICE / 10000, 0) * 10000 as PRICE_GROUP, COUNT(*) as PRODUCTS
# FROM PRODUCT
# GROUP BY PRICE_GROUP
# ORDER BY PRICE_GROUP

SELECT FLOOR(PRICE / 10000) * 10000 as PRICE_GROUP, COUNT(*) as PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP